src/adminactions/urls.py
from django.urls import re_path

from .views import format_date

urlpatterns = (re_path(r"^s/format/date/$", format_date, name="adminactions.format_date"),)

demo/demoproject/demoapp/models.py
from django.contrib.auth.models import User
from django.db import models


class DemoModel(models.Model):
    char = models.CharField(max_length=255)
    integer = models.IntegerField()
    logic = models.BooleanField()
    null_logic = models.NullBooleanField()
    date = models.DateField()
    datetime = models.DateTimeField()
    time = models.TimeField()
    decimal = models.DecimalField(max_digits=10, decimal_places=3)
    email = models.EmailField()
    #    filepath = models.FilePathField(path=__file__)
    float = models.FloatField()
    bigint = models.BigIntegerField()
    ip = models.IPAddressField()
    generic_ip = models.GenericIPAddressField()
    url = models.URLField()
    text = models.TextField()

    unique = models.CharField(max_length=255, unique=True)
    nullable = models.CharField(max_length=255, null=True)
    blank = models.CharField(max_length=255, blank=True, null=True)
    not_editable = models.CharField(max_length=255, editable=False, blank=True, null=True)
    choices = models.IntegerField(choices=((1, 'Choice 1'), (2, 'Choice 2'), (3, 'Choice 3')))

    class Meta:
        app_label = 'demoapp'


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    note = models.CharField(max_length=10, blank=True)

    class Meta:
        app_label = 'demoapp'


class UserDetail(models.Model):
    user = models.ForeignKey(User)
    note = models.CharField(max_length=10, blank=True)

    class Meta:
        app_label = 'demoapp'

src/adminactions/models.py
from django.db.models.signals import post_migrate

from . import config, consts, perms


def create_extra_permissions_handler(sender, **kwargs):
    global TOTAL_MODELS, COUNTER
    if config.AA_PERMISSION_HANDLER == consts.AA_PERMISSION_CREATE_USE_SIGNAL:
        perms.create_extra_permissions()
    else:
        post_migrate.disconnect(dispatch_uid="adminactions.create_extra_permissions")


post_migrate.connect(
    create_extra_permissions_handler,
    dispatch_uid="adminactions.create_extra_permissions",
)

src/adminactions/forms.py
import csv

from django import forms
from django.core.serializers import get_serializer_formats
from django.forms.models import ModelForm
from django.forms.widgets import SelectMultiple
from django.utils import formats
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

from .api import delimiters, quotes
from .utils import get_ignored_fields


class GenericActionForm(ModelForm):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)
    select_across = forms.BooleanField(
        label="",
        required=False,
        initial=0,
        widget=forms.HiddenInput({"class": "select-across"}),
    )
    action = forms.CharField(label="", required=True, initial="", widget=forms.HiddenInput())

    def configured_fields(self):
        return [field for field in self if not field.is_hidden and field.name.startswith("_")]

    @cached_property
    def model_field_names(self):
        ignored_fields = {
            "select_accross",
            "action",
            *get_ignored_fields(self._meta.model, "UPDATE_ACTION_IGNORED_FIELDS"),
        }
        return [f.name for f in self._meta.model._meta.get_fields() if f.name not in ignored_fields]

    def model_fields(self):
        # field_names = [f.name for f in self._meta.model._meta.get_fields() if f.name not in self.model_field_names]
        return [field for field in self if field.name in self.model_field_names]


class CSVConfigForm(forms.Form):
    header = forms.BooleanField(label=_("Header"), required=False)
    delimiter = forms.ChoiceField(
        label=_("Delimiter"), choices=list(zip(delimiters, delimiters)), initial=","
    )
    quotechar = forms.ChoiceField(label=_("Quotechar"), choices=list(zip(quotes, quotes)), initial="'")
    quoting = forms.TypedChoiceField(
        coerce=int,
        label=_("Quoting"),
        choices=(
            (csv.QUOTE_ALL, _("All")),
            (csv.QUOTE_MINIMAL, _("Minimal")),
            (csv.QUOTE_NONE, _("None")),
            (csv.QUOTE_NONNUMERIC, _("Non Numeric")),
        ),
        initial=csv.QUOTE_ALL,
    )

    escapechar = forms.ChoiceField(label=_("Escapechar"), choices=(("", ""), ("\\", "\\")), required=False)

    def clean_escapechar(self):
        return self.cleaned_data["escapechar"] or None

    def csv_fields(self):
        return [
            field
            for field in self
            if field.name
            in [
                "header",
                "delimiter",
                "quotechar",
                "quoting",
                "escapechar",
            ]
        ]


class CSVOptions(CSVConfigForm):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)
    select_across = forms.BooleanField(
        label="",
        required=False,
        initial=0,
        widget=forms.HiddenInput({"class": "select-across"}),
    )
    action = forms.CharField(label="", required=True, initial="", widget=forms.HiddenInput())

    datetime_format = forms.CharField(
        label=_("Datetime format"), initial=formats.get_format("DATETIME_FORMAT")
    )
    date_format = forms.CharField(label=_("Date format"), initial=formats.get_format("DATE_FORMAT"))
    time_format = forms.CharField(label=_("Time format"), initial=formats.get_format("TIME_FORMAT"))
    columns = forms.MultipleChoiceField(label=_("Columns"), widget=SelectMultiple(attrs={"size": 20}))


class XLSOptions(forms.Form):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)
    select_across = forms.BooleanField(
        label="",
        required=False,
        initial=0,
        widget=forms.HiddenInput({"class": "select-across"}),
    )
    action = forms.CharField(label="", required=True, initial="", widget=forms.HiddenInput())

    header = forms.BooleanField(label=_("Header"), required=False)
    use_display = forms.BooleanField(label=_("Use display"), required=False)
    columns = forms.MultipleChoiceField(label=_("Columns"), widget=SelectMultiple(attrs={"size": 20}))


class FixtureOptions(forms.Form):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)
    select_across = forms.BooleanField(
        label="",
        required=False,
        initial=0,
        widget=forms.HiddenInput({"class": "select-across"}),
    )
    action = forms.CharField(label="", required=True, initial="", widget=forms.HiddenInput())

    use_natural_pk = forms.BooleanField(label=_("Use Natural Primary Keys"), required=False)
    use_natural_fk = forms.BooleanField(label=_("Use Natural Foreign Keys"), required=False)
    on_screen = forms.BooleanField(label="Dump on screen", required=False)
    add_foreign_keys = forms.BooleanField(required=False)

    indent = forms.IntegerField(required=True, max_value=10, min_value=0)
    serializer = forms.ChoiceField(choices=list(zip(get_serializer_formats(), get_serializer_formats())))

src/adminactions/views.py
from datetime import datetime

from django.http import HttpResponse
from django.utils import dateformat


def format_date(request):
    d = datetime.now()
    return HttpResponse(dateformat.format(d, request.GET.get("fmt", "")))

src/adminactions/templates/adminactions/any_model.html
{% extends "admin/change_form.html" %}
{% load i18n admin_modify static %}
{% block extrahead %}{{ block.super }}
    <style type="text/css">
        #col1 {
            float: left;
            width: 70%;
        }

        #col2 {
            float: right;
            width: 30%;
        }
        #col2 select {
            width: 100%;
        }
    </style>
    <script language="javascript" type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    <script language="javascript" type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
    <script language="javascript" type="text/javascript" src="{% static 'adminactions/js/massupdate.js' %}"></script>
    <!--<script language="javascript" type="text/javascript" src="/media/js/admin/DateTimeShortcuts.js"></script>-->
{% endblock %}

{% block breadcrumbs %}{% if not is_popup %}
    <div class="breadcrumbs">
        <a href="../../../">{% trans "Home" %}</a> &rsaquo;
        <a href="../../">{{ app_label|capfirst|escape }}</a> &rsaquo;
        <a href="../">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
        Mass Update
    </div>
{% endif %}{% endblock %}

{% block content %}
    {% if form.subject.errors %}
        <ol>
            {% for error in form.subject.errors %}
                <li><strong>{{ error|escape }}</strong></li>
            {% endfor %}
        </ol>
    {% endif %}

    <div id='col1'>
        <form action="../" method="post">
            {% csrf_token %}
            <table>
                {% for field in adminform.form.configured_fields %}
                    <tr>
                        <td>{% if field.field.required %}
                            <b>{% endif %} {{ field.label_tag }}{% if field.field.required %}</b>{% endif %}  </td>
                        <td colspan="3">
                            {{ field.errors }}
                            {{ field }}&nbsp;<span class="help">{{ field.help_text }}</span>
                        </td>
                    </tr>
                {% endfor %}
                <tr><td colspan="4"><hr/></td></tr>
                <tr><th>field name </th><th>update</th><th>new value</th><th>existing values <small><i>(some of the most used )</i></small></th></tr>
                {% for field in adminform.form.model_fields %}
                    <tr class="{{ field.name }}-row">
                        <td>{% if field.field.required %}
                            <b>{% endif %} {{ field.label_tag }}{% if field.field.required %}</b>{% endif %}  </td>
                        <td class='col_enabler'><input type="checkbox" name="chk_id_{{ field.name }}" class="enabler"></td>
                        <td class='col_field field-{{ field.name }}-value'>{{ field.errors }}
                            {{ field }}&nbsp;</td>
                        </td>

                    </tr>
                {% endfor %}
            </table>
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            <input type="hidden" name="action" value="{{ action }}"/>
            <input type="submit" name="apply" value="{% trans 'Update records' %}"/>
        </form>
    </div>
    <div id='col2'>
        Selected records:
        <select size="30">
            {% for el in selection %}
                <option>{{ el }}</option>
            {% endfor %}
        </select>


    </div>
{% endblock %}

src/adminactions/templates/adminactions/bulk_update.html
{% extends "admin/change_form.html" %}
{% load i18n admin_modify actions massupdate static %}
{% block extrahead %}{{ block.super }}
  <meta name="opts.label" content="{{ opts.label }}">
{% endblock %}

{% block breadcrumbs %}{% if not is_popup %}
  <div class="breadcrumbs">
    <a href="../../">{% trans "Home" %}</a> &rsaquo;
    <a href="../">{{ app_label|capfirst|escape }}</a> &rsaquo;
    <a href=".">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
    {{ action_short_description|capfirst }}
  </div>
{% endif %}{% endblock %}

{% block content %}
  {% if form.subject.errors %}
    <ol>
      {% for error in form.subject.errors %}
        <li><strong>{{ error|escape }}</strong></li>
      {% endfor %}
    </ol>
  {% endif %}
  {{ form.non_field_errors }}
        <div>Settings: <small>
        <select id="sel-cmd">
          <option></option>
          <option>clear</option>
          <option>default</option>
          <option>saved</option>
        </select>
      </small></div>
  <form action="." method="post" enctype="multipart/form-data" id="bulk-update">
    <div id="col1">
      {% csrf_token %}
      <table class="mass-update">
      <tr><th colspan="3" class="title">Configuration</th></tr>
        {% for field in adminform.form %}
          {% if field.field.widget.input_type == "hidden" %}
            {{ field }}
          {% else %}
            <tr>
              <td>{{ field.label_tag }}</td>
              <td colspan="4">
                {{ field.errors }}
                {{ field }}&nbsp;<div class="help">{{ field.help_text }}</div>
              </td>
            </tr>
          {% endif %}
        {% endfor %}
        <tr>
          <th colspan="4" class="title">Columns Mapping</th>
        </tr>
      <tr>
        <td colspan="4" class="title">{{ map_form.index_field.errors }}</td>
      </tr>
        <tr>
          <th>field name</th>
          <th>Use for index</th>
          <th>Column name</th>
        </tr>
        {% for field in map_form %}
          {% if field.name != "index_field" %}
            <tr class="{{ field.name }}-row">
              <td>{% if field.field.required %}<b>{% endif %}
                {{ field.label_tag }}{% if field.field.required %}</b>{% endif %}  </td>
              <td class='col_enabler'>
                <input type="checkbox" name="fld-index_field" value="{{ field.name }}">
              </td>
              <td data-col="{{ field.name }}" class='col_field field-{{ map_form.prefix }}-{{ field.name }}-value'>
                {{ field.errors }}{{ field }}&nbsp;
              </td>
            </tr>
          {% endif %}
        {% endfor %}
      </table>
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}
      <input type="submit" name="apply" value="Update {{ selection.count }} records"/>
    </div>
    <div id="col2">
      <table>
                <tr>
                  <th colspan="2"  class="title"><h3>CSV Options</h3></th>
                </tr>
        {% for field in csv_form %}
          <tr>
            <td>{{ field.label_tag }}</td>
            <td colspan="4">
              {{ field.errors }}
              {{ field }}&nbsp;<span class="help">{{ field.help_text }}</span>
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </form>
{% endblock %}

src/adminactions/templates/adminactions/bulk_update_results.html
{% extends "admin/change_form.html" %}
{% load i18n admin_modify actions massupdate static %}
{% block extrahead %}{{ block.super }}
  <meta name="opts.label" content="{{ opts.label }}">
  {{ media }}
{% endblock %}

{% block breadcrumbs %}{% if not is_popup %}
  <div class="breadcrumbs">
    <a href="../../">{% trans "Home" %}</a> &rsaquo;
    <a href="../">{{ opts.app_label|capfirst|escape }}</a> &rsaquo;
    <a href=".">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
    {{ action_short_description|capfirst }} &rsaquo; Simulate
  </div>
{% endif %}{% endblock %}

{% block content %}
  {#  {'updated': [{'char': 'AAAA', 'id': '3'}], 'errors': [], 'missing': [], 'duplicates': [], 'changes': {<DemoModel: DemoModel object (3)>: <DemoModel: DemoModel object (3)>}}#}
  {#  {{ results }}#}
  <h1>Bulk Update results {% if dry_run %}(simulated) {% endif %}</h1>
  <table class="bulk-update-results">
    <thead>
    <tr>
      <th>Key</th>
      <th>Changes
      </th>
    </tr>
    </thead>
    {% for key, changes in results.changes.items %}
      <tr>
        <td>{{ key }}</td>
        <td>
          <table>
            {% for fld, values in changes.items %}
              <tr>
                <td>{{ fld }}</td>
                <td>{{ values.0 }}</td>
                <td>{{ values.1 }}</td>
              </tr>
            {% endfor %}
          </table>
        </td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

src/adminactions/templates/adminactions/export_csv.html
{% extends "admin/change_form.html" %}
{% load i18n admin_modify admin_urls %}{% load url from aa_compat %}
{% block extrahead %}{{ block.super }}
    <style type="text/css">
        #form {
            float: left;
            width: 40%;
        }

        #legend {
            float: left;
            width: 60%;
        }
    </style>
    {% url 'adminactions.format_date' as url_format_date %}
    {% if url_format_date %}
    <script type="text/javascript">
        (function ($) {
            $(document).ready(function ($) {
{#                $('#id_datetime_format, #id_date_format, #id_time_format,').after('&nbsp;&nbsp;<span class="sample"></span>');#}
                var _url = "{{ url_format_date }}";
                var get_format = function (sender) {
                    $.get(_url, {'fmt':$(sender).val()},
                            function (data) {
                                $(sender).next('.sample').html(data);
                            }
                    );
                };
                $('#id_datetime_format, #id_date_format, #id_time_format').after('&nbsp;&nbsp;<span class="sample"></span>').keyup(function () {
                    clearTimeout($(this).data('timer'));
                    var target = $(this);
                    var wait = setTimeout(function () {
                        get_format(target)
                    }, 500);
                    $(this).data('timer', wait);
                }).trigger('keyup');
            });
        })(django.jQuery);

    </script>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}{% if not is_popup %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% trans "Home" %}</a> &rsaquo;
        <a href="{% url 'admin:index' %}{{ app_label}}">{{ app_label|capfirst }}</a> &rsaquo;
        {% if has_change_permission %}<a
                href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %} &rsaquo;
	{{ action_short_description|capfirst }}
    </div>
{% endif %}{% endblock %}

{% block content %}
    {% if adminform.form.subject.errors %}
        <ol>
            {% for error in adminform.form.subject.errors %}
                <li><strong>{{ error|escape }}</strong></li>
            {% endfor %}
        </ol>
    {% endif %}
    <div id='form'>
        <form action="" method="post" id="export-form">
            {% csrf_token %}
            <table>
                {{ adminform.form }}
            </table>
{#            <input type="hidden" name="action" value="{{ action }}"/>#}
            <input type="submit" name="apply" value="{% trans 'Export' %}"/>
        </form>
    </div>
    {% url 'adminactions.format_date' as url_format_date %}
    {% if url_format_date %}
    <div id='legend-date'>
    <table xmlns="http://www.w3.org/1999/xhtml" lass="doctable table">
    <caption><b>The following characters are recognized in the
        <i><tt class="parameter">format</tt></i> parameter string</b></caption>

    <thead valign="middle">
    <tr valign="middle">
        <th><i></i>{% trans "character" %}</th>
        <th>{% trans "Description" %}</th>
        <th>{% trans "Example returned values" %}</th>
    </tr>

    </thead>

    <tbody valign="middle" class="tbody">
    <tr valign="middle">
        <td align="center"><em class="emphasis">{% trans "Day" %}</em></td>
        <td align="left">---</td>
        <td align="left">---</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>d</i></td>
        <td align="left">{% trans "Day of the month, 2 digits with leading zeros" %}</td>
        <td align="left"><i>01</i> {% trans "to" %} <i>31</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>D</i></td>
        <td align="left">{% trans "A textual representation of a day, three letters" %}</td>
        <td align="left"><i>{% trans "Mon" %}</i>{% trans "through" %}<i>{% trans "Sun" %}</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>j</i></td>
        <td align="left">{% trans "Day of the month without leading zeros" %}</td>
        <td align="left"><i>1</i> {% trans "to" %}<i>31</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>l</i> (lowercase 'L')</td>
        <td align="left">{% trans "A full textual representation of the day of the week" %}</td>
        <td align="left"><i>{% trans "Sunday" %}</i>{% trans "through" %}<i>{% trans "Saturday" %}</i></td>
    </tr>

    <tr>
        <td align="left"><i>1</i>{% trans "for Monday through" %}<i>7</i>{% trans "for Sunday"%}</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>S</i></td>
        <td align="left">{% trans "English ordinal suffix for the day of the month, 2 characters" %}</td>
        <td align="left">
            <i>st</i>, <i>nd</i>, <i>rd</i> or
            <i>th</i>.{% trans "Works well with" %} <i>j</i>
        </td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>w</i></td>
        <td align="left">{% trans "Numeric representation of the day of the week" %}</td>
        <td align="left"><i>0</i>{% trans "(for Sunday) through" %}<i>6</i>{% trans "(for Saturday)" %}</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>z</i></td>
        <td align="left">{% trans "The day of the year (starting from 0)" %}</td>
        <td align="left"><i>0</i>{% trans "through" %}<i>365</i></td>
    </tr>

    <tr valign="middle">
        <td align="center"><em class="emphasis">{% trans "Week" %}</em></td>
        <td align="left">---</td>
        <td align="left">---</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>W</i></td>
        <td align="left">{% trans "ISO-8601 week number of year, weeks starting on Monday (added in PHP 4.1.0)"%}</td>
        <td align="left">{% trans "Example:" %} <i>42</i> {% trans "(the 42nd week in the year)" %}</td>
    </tr>

    <tr valign="middle">
        <td align="center"><em class="emphasis">{% trans "Month" %}</em></td>
        <td align="left">---</td>
        <td align="left">---</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>F</i></td>
        <td align="left">{% trans "A full textual representation of a month, such as January or March" %}</td>
        <td align="left"><i>{% trans "January" %}</i> {% trans "through" %}<i>{% trans "December" %}</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>m</i></td>
        <td align="left">{% trans "Numeric representation of a month, with leading zeros" %}</td>
        <td align="left"><i>01</i>{% trans " through" %} <i>12</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>M</i></td>
        <td align="left">{% trans "A short textual representation of a month, three letters" %}</td>
        <td align="left"><i>{% trans "Jan" %}</i>{% trans " through" %}<i>{% trans "Dec" %}</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>n</i></td>
        <td align="left">{% trans "Numeric representation of a month, without leading zeros" %}</td>
        <td align="left"><i>1</i>{% trans " through" %}<i>12</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>t</i></td>
        <td align="left">{% trans "Number of days in the given month" %}</td>
        <td align="left"><i>28</i>{% trans " through" %} <i>31</i></td>
    </tr>

    <tr valign="middle">
        <td align="center"><em class="emphasis">{% trans "Year" %}</em></td>
        <td align="left">---</td>
        <td align="left">---</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>L</i></td>
        <td align="left">{% trans "Whether it's a leap year"%}</td>
        <td align="left"><i>1</i>{% trans " if it is a leap year, "%}<i>0</i> {% trans "otherwise."%}</td>
    </tr>

    <tr>
        <td align="left">{% trans "Examples:" %}<i>{% trans "1999" %}</i>{% trans " or" %} <i>{% trans "2003" %}</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>Y</i></td>
        <td align="left">{% trans "A full numeric representation of a year, 4 digits"%}</td>
        <td align="left">{% trans "Examples: "%}<i>{% trans "1999"%}</i> {% trans "or" %} <i>2003</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>y</i></td>
        <td align="left">{% trans "A two digit representation of a year" %}</td>
        <td align="left">{% trans "Examples: <i>99</i> or <i>03</i></td>
    </tr>

    <tr valign="middle">
        <td align="center"><em class="emphasis">{% trans "Time" %}</em></td>
        <td align="left">---</td>
        <td align="left">---</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>a</i></td>
        <td align="left">{% trans "Lowercase Ante meridiem and Post meridiem" %}</td>
        <td align="left"><i>am</i> {% trans "or " %}<i>pm</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>A</i></td>
        <td align="left">{% trans "Uppercase Ante meridiem and Post meridiem" %}</td>
        <td align="left"><i>AM</i>{% trans " or " %}<i>PM</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>B</i></td>
        <td align="left">{% trans "Swatch Internet time" %}</td>
        <td align="left"><i>000</i>{% trans " through " %}<i>999</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>g</i></td>
        <td align="left">{% trans "12-hour format of an hour without leading zeros" %}</td>
        <td align="left"><i>1</i>{% trans " through " %}<i>12</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>G</i></td>
        <td align="left">{% trans "24-hour format of an hour without leading zeros" %}</td>
        <td align="left"><i>0</i>{% trans " through " %}<i>23</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>h</i></td>
        <td align="left">{% trans "12-hour format of an hour with leading zeros" %}</td>
        <td align="left"><i>01</i>{% trans " through " %}<i>12</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>H</i></td>
        <td align="left">{% trans "24-hour format of an hour with leading zeros" %}</td>
        <td align="left"><i>00</i>{% trans " through " %}<i>23</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>i</i></td>
        <td align="left">{% trans "Minutes with leading zeros" %}</td>
        <td align="left"><i>00</i>{% trans " to " %}<i>59</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>s</i></td>
        <td align="left">{% trans "Seconds, with leading zeros" %}</td>
        <td align="left"><i>00</i>{% trans " through" %} <i>59</i></td>
    </tr>

    <tr valign="middle">
        <td align="center"><em class="emphasis">{% trans "Timezone" %}</em></td>
        <td align="left">---</td>
        <td align="left">---</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>I</i>{% trans " (capital i)" %}</td>
        <td align="left">{% trans "Whether or not the date is in daylight saving time" %}</td>
        <td align="left"><i>1</i>{% trans " if Daylight Saving Time, <i>0</i> otherwise." %}</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>O</i></td>
        <td align="left">{% trans "Difference to Greenwich time (GMT) in hours" %}</td>
        <td align="left">{% trans "Example: " %}<i>+0200</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>T</i></td>
        <td align="left">{% trans "Timezone abbreviation" %}</td>
        <td align="left">{% trans "Examples: " %}<i>EST</i>, <i>MDT</i> ...</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>Z</i></td>
        <td align="left">{% trans "Timezone offset in seconds. The offset for timezones west of UTC is always negative, and for those east of UTC is always positive." %}</td>
        <td align="left"><i>-43200</i>{% trans "through " %}<i>50400</i></td>
    </tr>

    <tr valign="middle">
        <td align="center"><em class="emphasis">{% trans "Full Date/Time" %}</em></td>
        <td align="left">---</td>
        <td align="left">---</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>r</i></td>
        <td align="left"><a class="link external" href="http://www.faqs.org/rfcs/rfc2822">» RFC 2822</a>{% trans "formatted date" %}</td>

        <td align="left">{% trans "Example: " %}<i>{% trans "Thu, 21 Dec 2000 16:01:07 +0200" %}</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>U</i></td>
        <td align="left">{% trans "Seconds since the Unix Epoch (January 1 1970 00:00:00 GMT)" %}</td>
        <td align="left">{% trans "See also" %} <span class="function">
          <a class="function" href="function.time.php">time()</a></span>
        </td>

    </tr>

    </tbody>

    </table>

    </div>
    {% endif  %}
{% endblock %}